### ISSUE TITLE
feat: system metrics for optmize

### ISSUE THREAD

**Issue by bohutang** [databendlabs/databend#11460]
**Summary**

This system metrics table should tell us:
1. What's the metrics of the Databend
2. Do we need to do: optimize/purge/vacuum/compaction

**Comment by flaneur2020** [comment]
i guess the number of blocks / segments is useful enough for many use cases about background work scheduling & performance diagnosis

**Comment by ZhiHanZ** [comment]
I don't think the metrics is a good first issue, it require non-trivial amount of understanding about log structured table and cloud storage...
