### ISSUE TITLE
Refactor fuse pruner

### ISSUE THREAD

**Issue by SkyFan2002** [databendlabs/databend#13853]
**Summary**
Currently pruning process is blocking the entire pipeline. By integrating the pruning process into the pipeline, the parallelism of pruning and query execution can be enhanced.

Related PR: https://github.com/datafuselabs/databend/pull/11552

**Comment by Xuanwo** [comment]
Hi, when refactoring the fuse pruner, let's keep in mind that Databend has multiple engines like Hive Table, Delta Table, and Iceberg Table. It would be better to refactor in a way that can be shared among them.

cc @SkyFan2002 @dqhl76 @sundy-li

**Comment by dqhl76** [comment]
> It would be better to refactor in a way that can be shared among them.

I am planing to split the different table engines's pruning process into processors. Some of them may be could be refactored as a sharing processor. Plan to first start with fuse engine. Thanks for the reminding, will keep in mind.

**Comment by dqhl76** [comment]
Duplicate with https://github.com/databendlabs/databend/issues/16626. Tracking in that.
