### ISSUE TITLE
feat: merge into returns how many rows update/delete/inserted 

### ISSUE THREAD

**Issue by bohutang** [databendlabs/databend#13855]
**Summary**
<img width="942" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/fa3a7e2a-529e-40a5-99b3-734e4477d64d">

**Comment by JackTan25** [comment]
well, I think we should change this:
```sql
mysql> merge into  tb_01 as T using ( select * from tmp_01) as S on t.id = s.id when matched then update * when not matched then insert *;
Query OK, 2 rows affected (0.15 sec)
```
to
```sql
mysql> merge into  tb_01 as T using ( select * from tmp_01) as S on t.id = s.id when matched then update * when not matched then insert *;
number of rows inserted xx rows affected
number of rows updated xx rows affected
number of rows deleted xx rows affected
Query OK, 2 rows affected (0.15 sec)
```

**Comment by BohuTANG** [comment]
> well, I think we should change `merge into` to output a table.

But note that the output table columns is dynamic adjust by the `MERGE` clause which cases have.
If we have this, the wizard also can check the MERGE INTO returns table.

**Comment by JackTan25** [comment]
> > well, I think we should change `merge into` to output a table.
> 
> But note that the output table columns is dynamic adjust by the `MERGE` clause which cases have. If we have this, the wizard also can check the MERGE INTO returns table.

yes, it means when once is zero, we shouldn't output it.
