### ISSUE TITLE
Feature: function about convert_timezone

### ISSUE THREAD

**Issue by TCeason** [databendlabs/databend#16177]
**Summary**

Now Databend support to_timestamp can convert string to current timezone with setting `timezone`.

And convert_timezone is support to convert given time to target timezone.

ref: https://docs.snowflake.com/en/sql-reference/functions/convert_timezone

```sql
convert_timezone('target_timezone', 'timestamp');
```

**Comment by florann** [comment]
Hey, 
I would like to work on this issue. 
Can you please assign it to me ?

**Comment by florann** [comment]
Hello,
My pull request is ready with all check done and just waiting for a review. 
Tanks.

**Comment by TCeason** [comment]
> Hello,
> 
> My pull request is ready with all check done and just waiting for a review. 
> 
> Tanks.

Need test :) you can add it in datetime_tz.test in suite dir

**Comment by florann** [comment]
I think something is wrong with this new method "convert_timezone".
I tried different tests and every of them ends "this function does not exist" :/

**Comment by TCeason** [comment]
> I think something is wrong with this new method "convert_timezone". I tried different tests and every of them ends "this function does not exist" :/

You can read this doc first: https://docs.databend.com/guides/community/contributor/how-to-write-scalar-functions

And then can ref function: "to_timestamp": https://github.com/datafuselabs/databend/blob/4b2e844c728f9f4875ce3f61458e7a7d1c6554f4/src/query/functions/src/scalars/datetime.rs#L146

Now ctx.func_ctx.tz.tz is a user setting timezone.

In convert_timezone, we should :

1. cast the string to timestamp
2. convert the timestamp with target timezone.

After impl the function, add test in https://github.com/datafuselabs/databend/blob/4cd1de74fa42a31bb61d0d7d46b7c108a11471ac/tests/sqllogictests/suites/query/functions/02_0012_function_datetimes_tz.test#L658

**Comment by TCeason** [comment]
convert_timezone with three args is hard to impl now. Because now databend only store timestamp in storage.
