### ISSUE TITLE
[config] consider rename store_api_* to store_* for query config

### ISSUE THREAD

**Issue by bohutang** [databendlabs/databend#1623]
**Summary**

For config, the name with prefix `store_api_yy` appears to be a config item that exposes for others, the name is suite for datafuse-store not query.

**Comment by BohuTANG** [comment]
> @BohuTANG I want to work on this. Please how do i locate the file were the changes needs to be made

@Onyinye91-ctrl Hi!
Thank you, this task is done(I'm already in progress and the issue is a bit difficult when i saw this comments), we could look for other tasks which labeled with `good first issue`.
This guide line may be helpful:
https://datafuse.rs/development/contributing/
