### ISSUE TITLE
feature: Settings clause

### ISSUE THREAD

**Issue by sundy-li** [databendlabs/databend#16387]
**Summary**

syntax
```
SETTINGS ( parameter = value [ , parameter = value ] )  Statement
```

SETTINGS clause works only in Statement of:

```
SELECT
INSERT 
MergeINTO
COPY
UPDATE
DELETE
CREATE TABLE 
EXPLAIN
```

examples:

```
settings (max_thread = 3,  enable_loser_tree_merge_sort = 1) select  1 + 1 
```

```
settings (max_thread = 3,  enable_loser_tree_merge_sort = 1)  copy into ....
```

We already had `set_var_hints` now, but the syntax is not friendly.
Settings could also be parsed into `HintItem`. 
 
Any advice?  cc @zhang2014  @andylokandy  

Refer to https://docs.yellowbrick.com/6.8.1/ybd_sqlref/setting_clause.html

**Comment by BohuTANG** [comment]
Why not use set_var to do it?

**Comment by zhang2014** [comment]
LGTM

**Comment by TCeason** [comment]
Maybe add a new type in SetType is better than HintItem?

```rust
pub enum SetType {
    #[default]
    SettingsSession,
    SettingsGlobal,
    Variable,
    SettingsQuery,
}
```

And if user use settings and hints , the hints will be invalid.
