### ISSUE TITLE
Feature: Date Functions to support week as a unit

### ISSUE THREAD

**Issue by Shanmugavel-J** [databendlabs/databend#16402]
**Summary**

Not able to perform Date operations with unit week. Can it be added as a additional support for `week`.

QUERY: `SELECT DATE_ADD('week', 1, TODAY());`

```
SQL Error [1008]: Query failed (#7068da3e-54f5-4c3f-8c3d-4e9c0d2b99bc): error: 
  --> SQL:1:8
  |
1 | SELECT DATE_ADD('week', 1, TODAY())
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function `add_weeks` does not exist
```

**Comment by TCeason** [comment]
Maybe you can try:

```sql
root@localhost:8000/default> SELECT DATE_ADD('day', 7, TODAY());

SELECT
  DATE_ADD('day', 7, TODAY())

-[ RECORD 1 ]-----------------------------------
DATE_ADD(DAY, 7, today()): 2024-09-12

```

And I think it's a good first issue.

**Comment by Shanmugavel-J** [comment]
Yes @TCeason This would be a good addition for DATE functionality to ADD ON. Thanks!

**Comment by ca1eigh** [comment]
Hi! Is this issue still open? I would like to work on it. Thanks!

**Comment by TracyZYJ** [comment]
Please assign me 😊
