### ISSUE TITLE
feature: short sql length setting

### ISSUE THREAD

**Issue by BohuTANG** [databendlabs/databend#16462]
**Summary**

Now, the sql truncate to 128 bytes is too short for many cases, we can add a new settings for that.
https://github.com/datafuselabs/databend/blob/8eaf57b52cc56929291d5d3b25c696c0bd4a2252/src/common/base/src/base/string.rs#L197

```
("short_sql_max_length", DefaultSettingValue {
    value: UserSettingValue::UInt64(128), // Default max length
    desc: "Sets the maximum length for truncating SQL queries in short_sql function.",
    mode: SettingMode::Both,
    range: Some(SettingRange::Numeric(1..=1024*1024)),
}),

```

**Comment by arkzuse** [comment]
hi, i would like to take this issue.

**Comment by arkzuse** [comment]
just want to make sure i have to add the setting to `src/query/settings/src/settings_default.rs` right. Is there anything else I need to consider?

**Comment by arkzuse** [comment]
do we need a setter for this?

**Comment by arkzuse** [comment]
do we need a setter for this?
