### ISSUE TITLE
feature: DATE_DIFF function

### ISSUE THREAD

**Issue by BohuTANG** [databendlabs/databend#16534]
**Summary**

Databend lacks a DATE_DIFF function, though it supports direct arithmetic on dates and times (e.g., TO_DATE(NOW()) - 2 for two days ago). However, users may find this conversion difficult, see: https://docs.databend.com/sql/sql-functions/datetime-functions/date-diff

Proposal add a `DATE_DIFF` function:
```
DATE_DIFF(<date_or_time_part>, <date_or_time_expr1>, <date_or_time_expr2>)
```
Similar to [Snowflake's DATEDIFF](https://docs.snowflake.com/en/sql-reference/functions/datediff) function, this will simplify date and time arithmetic for users.

**Comment by chagelo** [comment]
I would like to have a try.

**Comment by chagelo** [comment]
> I would like to have a try.

So all calculation should happen in `src/query/functions/src/scalars/datetime.rs`? in the `impl_register_arith_functions`?

**Comment by chagelo** [comment]
Should `select to_date('2024-02-29') + - to_date('2025-02-28');` be valid or invalid? I mean the add operation between two date.

**Comment by TCeason** [comment]
> 1. Should `select to_date('2024-02-29') + - to_date('2025-02-28');` be valid or invalid? I mean the add operation between two date.

select to_date('2024-02-29') - to_date('2025-02-28'); is valid.

select to_date('2024-02-29') + to_date('2025-02-28'); is invalid.

**Comment by TCeason** [comment]
https://github.com/databendlabs/databend/pull/16560
