### ISSUE TITLE
Feature: Support for partitioned Delta table

### ISSUE THREAD

**Issue by xixipi-lining** [databendlabs/databend#16549]
**Summary**

The current Delta engine does not support partitioned Delta tables, and queries on partitioned Delta tables result in a full table scan.

databend-query version: databend-query v1.2.642-nightly-dd45c198ba(rust-1.81.0-nightly-2024-09-29T22:08:05.263157141Z)

**Comment by wubx** [comment]
Databend hides partitions, so users don’t need to worry about them. However, users still need to understand data loading and cluster keys.

**Comment by xixipi-lining** [comment]
Thank you for your reply. The data was not loaded into Databend but was queried directly.

https://docs.databend.com/guides/access-data-lake/delta

I query the Delta table through the documentation here.

**Comment by sundy-li** [comment]
@xixipi-lining  hi, it's fixed by #16621 , can you check this?

**Comment by xixipi-lining** [comment]
Things are looking good. Queries on partitions no longer scan the entire table. Awesome!
