### ISSUE TITLE
bug: Unable to get field named "114"

### ISSUE THREAD

**Issue by rad-pat** [databendlabs/databend#16564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

v1.2.642-nightly

### What's Wrong?

`APIError: ResponseError with 1006: Unable to get field named "114". Valid fields: []`

I've no idea what this is referring to. There is no field "114" within my query

### How to Reproduce?

Quite a long and complicated query using many CTE, this has been working fine on previous used version 1.2.635-nightly
```
CREATE OR REPLACE TABLE t1 (test bigint);

WITH cte1
AS (
	SELECT t1.test
	FROM t1
	WHERE t1.test = 0
	)
	,cte2
AS (
	SELECT cte1.test
	FROM cte1
	WHERE cte1.test = 1
	
	UNION ALL
	
	SELECT cte1.test
	FROM cte1
	WHERE cte1.test = 0
	)
SELECT *
FROM cte2;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
You can provide the taable structure and query SQL.

**Comment by rad-pat** [comment]
> You can provide the taable structure and query SQL.

@wubx , I managed to reproduce with a much simpler query. Issue updated

**Comment by xudong963** [comment]
Thanks for reporting @rad-pat , the reproduced case is really helpful! I've located the root reason, fixing is on the way.
