### ISSUE TITLE
bug: the group function does not return the correct result

### ISSUE THREAD

**Issue by cdmikechen** [databendlabs/databend#16563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

v1.2.615

### What's Wrong?

The cumulative (like for annual) sum function does not return the expected value:

databend: wrong result and not sure what to do with the result.
![image](https://github.com/user-attachments/assets/6e108531-35d6-4084-a29a-41fc64071f38)

postgresql: right result we expected.
![image](https://github.com/user-attachments/assets/a5d074a1-d527-4661-aaca-6ab2463baaca)

### How to Reproduce?

databend:
```sql
drop table test_group;
create table test_group (
  input_date date,
  value decimal(10,2)
);
insert into test_group values ('2024-01-01', 100),('2024-01-01', 200),('2024-01-02', 400),('2024-01-02', 800);

select input_date, sum(value), 
(select sum(value)
	    from test_group b
	    where b.input_date >= DATE_TRUNC(YEAR, input_date)
	      and b.input_date <= a.input_date) as total
from test_group a
group by input_date;
```

postgresql:
```sql
drop table test_group;
create table test_group (
  input_date date,
  value decimal(10,2)
);
insert into test_group values ('2024-01-01', 100),('2024-01-01', 200),('2024-01-02', 400),('2024-01-02', 800);

select input_date, sum(value), 
(select sum(value)
    from test_group b
    where b.input_date >= date_trunc('year', input_date)
      and b.input_date <= a.input_date) as total
from test_group a
group by input_date;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cdmikechen** [comment]
After validation of more row values, it appears that the result of sum is multiplied by the number of same date rows.

**Comment by sundy-li** [comment]
I tried latest version, seem the result is correct.

```
┌──────────────────────────────────────────────────────────┐
│  input_date  │      sum(value)     │        total        │
│   Date NULL  │ Decimal(38, 2) NULL │ Decimal(38, 2) NULL │
├──────────────┼─────────────────────┼─────────────────────┤
│ '2024-01-02' │ 1200.00             │ 1500.00             │
│ '2024-01-01' │ 300.00              │ 300.00              │
└──────────────────────────────────────────────────────────┘
2 rows result in 0.110 sec. Processed 12 rows, 12 B (109.36 rows/s, 1.61 KiB/s)
```

**Comment by cdmikechen** [comment]
https://github.com/user-attachments/assets/4fac0242-2cc3-47c1-be14-a988700d2e8f

Here is my test, my cluster size is meta * 3, query * 3. 
May I ask if you did the test under the condition of single machine?

**Comment by sundy-li** [comment]
Related to merge join in cluster mode.

**Comment by xudong963** [comment]
Added the issue to my lists, thanks for reporting @cdmikechen.
