### ISSUE TITLE
Issue with Converting Epoch Timestamp in Milliseconds to Date

### ISSUE THREAD

**Issue by Shanmugavel-J** [databendlabs/databend#16575]
**Summary**

Getting different value when converting the below specific epoch timestamp in milliseconds to date. The function provides correct value when trying without milliseconds for that specific year.

**Query:** `SELECT TO_TIMESTAMP(-7233803000);`

**Output:**  `1740-10-08 10:16:40.000`

**Query:** `SELECT TO_TIMESTAMP(-7233803);`

**Output:**  `1969-10-09 06:36:37.000`

Note: The epoch time actual date is 1969-10-09

**Comment by TCeason** [comment]
By design

https://docs.databend.com/sql/sql-functions/datetime-functions/to-timestamp

**Comment by Shanmugavel-J** [comment]
@TCeason In the sense is that it would give it wrong?

I could see the correct date for remaining timestamps but not for that specific year(didnt check all the dates but for one or two days).

**Comment by TCeason** [comment]
In doc

Range	Unit
x < 31,536,000,000	Seconds
31,536,000,000 ≤ x < 31,536,000,000,000	Milliseconds
x ≥ 31,536,000,000,000	Microseconds

**Comment by Shanmugavel-J** [comment]
Okay. But the epoch time could be in negative as well correct?

I had attached the below image the epoch for date 10-10-1969 is shown in it. When that value is copied and executed in databend i get a different output.

![image](https://github.com/user-attachments/assets/1636f77c-057e-4311-a3af-77e959982ead)

**Comment by Shanmugavel-J** [comment]
@TCeason could you please help me out with the above scenario?

**Comment by TCeason** [comment]
> could you please help me out with the above scenario?

It's python's result? Couldn't you provide some sql?

**Comment by TCeason** [comment]
> @TCeason Okay. But the epoch time could be in negative as well correct? And if you could see i did a conversion of a date to epoch
> 
> I had attached the below image the epoch for date 10-10-1969 is shown in it. When that value is copied and executed in databend i get a different output.
> 
> ![image](https://github.com/user-attachments/assets/1636f77c-057e-4311-a3af-77e959982ead)

getTime is?

**Comment by Shanmugavel-J** [comment]
It would fetch the time in milliseconds. And using that time in db fetch query. But i get a different time over there

**Comment by TCeason** [comment]
> It would fetch the time in milliseconds. And using that time in db fetch query. But i get a different time over there.
> 
> Query
> SELECT TO_TIMESTAMP(output of that function);

If the time is ms an easy way is convert to timestamp then convert to date type.

**Comment by Shanmugavel-J** [comment]
Yes but the output of that function lets say _-7191000000_ (10-10-1969)

But when it is converted using query 

SELECT TO_TIMESTAMP(-7191000000);

1742-02-15

**Comment by TCeason** [comment]
> In doc
> 
> Range	Unit
> x < 31,536,000,000	Seconds
> 31,536,000,000 ≤ x < 31,536,000,000,000	Milliseconds
> x ≥ 31,536,000,000,000	Microseconds

Try *1000.

**Comment by Shanmugavel-J** [comment]
Still it shows the same date -7191000000000 - 1742-02-15

-7191000000000 - 2197-11-15

**Comment by TCeason** [comment]
> Still it shows the same date 
> -7191000000000 - 1742-02-15
> 
> 7191000000000 - 2197-11-15

Got I will see it tomorrow
