### ISSUE TITLE
Feature: Support map lambda functions

### ISSUE THREAD

**Issue by b41sh** [databendlabs/databend#16639]
**Summary**

- `map_filter(map, lambda_expr)`
- `map_transform_keys(map, lambda_expr)`
- `map_transform_values(map, lambda_expr)`

for example:
```sql
SELECT map_filter({1:0,2:2,3:-1}, (k, v) -> k > v);
SELECT map_transform_keys({1:1,2:2,3:3}, (k, v) -> k + 1);
SELECT map_transform_values({1:1,2:2,3:3}, (k, v) -> k + v);
```

reference document:
https://docs.databricks.com/en/sql/language-manual/functions/map_filter.html
https://docs.databricks.com/en/sql/language-manual/functions/transform_keys.html
https://docs.databricks.com/en/sql/language-manual/functions/transform_values.html

**Comment by Dragonliu2018** [comment]
i want to try it
