### ISSUE TITLE
bug: merge query unable to run nested `and` or `or` conditions

### ISSUE THREAD

**Issue by anirudhsathya74** [databendlabs/databend#16675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

databend-driver==0.20.1
databend-py==0.6.2

### What's Wrong?

merge query is unable to handle `or` or `and` conditions nested inside another `or` or `and`. 
`AND (
                        COALESCE(col1::float64, 0) <>
                            (col2::float64 * col3)::float64
                        OR 
                        COALESCE(col1::float64, 0) <> ((col2::float64 * col3) -
                            CASE
                                WHEN is_null_value(col4) THEN 0
                                ELSE col4::float64
                            END)::float64
                        )`
                        
Something similar to this isn't working and giving error

`Query failed: QueryErrors{code=1001, message=Cannot downcast Filter to Join} cause: null`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
@anirudhsathya74 Hi, thanks for reporting, could you please provide a minimum reproducible case?

**Comment by anirudhsathya74** [comment]
I’m thinking my databend version is not up to date and causing the issue. Hence closing it until further notice
