### ISSUE TITLE
Feature: Add Support for INTERVAL Data Type - Already Supported in Parquet & Arrow

### ISSUE THREAD

**Issue by inviscid** [databendlabs/databend#16677]
**Summary**

Interval is a value type that Databend understands as it is used in date addition.  However, there is no current way to store an Interval value like can be done in Postgres.

While Snowflake and MySQL also do not support the Interval type, Postgres does and it makes life so much easier since it is quite common to store duration information.  Both Parquet and Arrow do support an Interval/Duration data type.

The Parquet standard does support an Interval data type as defined here: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#interval

Arrow also supports a Duration type with varying levels of resolution.  It would likely be safe to pick a reasonable default resolution for Arrow usage: https://arrow.apache.org/docs/python/generated/pyarrow.duration.html#pyarrow.duration.  This conversion function seems to suggest that might be milliseconds: https://arrow.apache.org/rust/parquet/arrow/arrow_writer/fn.get_interval_dt_array_slice.html

The ideal approach would be one where an Interval value could be marshalled and unmarshalled from Parquet using native Parquet and Arrow types.

**Comment by sundy-li** [comment]
New DataTypes could be supported after #16610 , we are still in a big refactoring stage.

**Comment by BohuTANG** [comment]
#16610 has been merged, and this feature is now ready to be added to the work queue.

**Comment by sundy-li** [comment]
Better do it after #16814

**Comment by inviscid** [comment]
@sundy-li now that #16814 is complete, do you have an estimate on when this might get some focus?

**Comment by sundy-li** [comment]
@TCeason  is already working on it.

We will support interval units via `months, days, or microseconds`

**Comment by inviscid** [comment]
@TCeason Sorry to bother you on this one.  We are trying to plan out migrations to Databend but we have a couple of projects that depend on the Interval data type being available.  Would it be realistic to see that new data type this week or is that too soon?  We would have to push the migrations to next year if we can't get testing done by next week.

Thanks...

**Comment by TCeason** [comment]
> @TCeason Sorry to bother you on this one.  We are trying to plan out migrations to Databend but we have a couple of projects that depend on the Interval data type being available.  Would it be realistic to see that new data type this week or is that too soon?  We would have to push the migrations to next year if we can't get testing done by next week.
> 
> 
> 
> Thanks...

This week I'm prioritizing this task. It is expected to be completed by the end of the week
