### ISSUE TITLE
Feature: Support function:  last_day, next_day and previous_day

### ISSUE THREAD

**Issue by wubx** [databendlabs/databend#16715]
**Summary**

- [ ] last_day https://docs.snowflake.com/en/sql-reference/functions/last_day 
- [ ] next_day https://docs.snowflake.com/en/sql-reference/functions/next_day
- [ ] previous_day https://docs.snowflake.com/en/sql-reference/functions/previous_day

**Comment by TCeason** [comment]
about last_day, can consider use https://github.com/datafuselabs/databend/blob/7a6f1fba12fa98c9d3a79698d59c249032123ddd/src/query/expression/src/utils/date_helper.rs#L331

**Comment by Freejww** [comment]
take
