### ISSUE TITLE
bug: need to remove single quotes for comment 

### ISSUE THREAD

**Issue by cdmikechen** [databendlabs/databend#16731]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

v1.2.642-nightly

### What's Wrong?

Table and column comments using jdbc are wrapped in single quotes, which are not actually comments and need to be remove. 
We found that the jdbc for mysql or databend is fetched from `information_schema.columns` and `information_schema.tables`.

https://github.com/databendlabs/databend/blob/3036fa8358af3c0f53021541dd9f2bb15c7596a2/src/query/storages/system/src/columns_table.rs#L207-L226

### How to Reproduce?

```sql
create table test_comment (a int comment 'test comment') COMMENT ='table comment'
```
trying to fix databend-jdbc issue https://github.com/databendlabs/databend-jdbc/pull/285 

We try to do it in a regular way can we change it in the relevant code? `REGEXP_REPLACE(comment, '^\\'(.+)\\'$', '$1')`

https://github.com/databendlabs/databend/blob/3036fa8358af3c0f53021541dd9f2bb15c7596a2/src/query/storages/information_schema/src/columns_table.rs#L29-L62

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
`system.columns` need to fix this bug
```

🐳 :) select comment  from system.tables where name  = 'test_comment';
┌───────────────┐
│    comment    │
│     String    │
├───────────────┤
│ table comment │
└───────────────┘

🐳 :) 🐳 :) select comment from system.columns where table = 'test_comment';
┌────────────────┐
│     comment    │
│     String     │
├────────────────┤
│ 'test comment' │
└────────────────┘
```
