### ISSUE TITLE
Feature: Support AWS Glue Catalog for Apache Iceberg

### ISSUE THREAD

**Issue by Rowlandev** [databendlabs/databend#16793]
Databend currently supports `rest` and `hms` when creating an Apache Iceberg catalog. However, it's not supported for AWS Glue.

My proposition is to enable a query like the following, or somethings similar for users using Glue:

```
CREATE CATALOG analytics_testing
TYPE = ICEBERG
CONNECTION = (
	DATABASE = '<glue database name as it is in s3>'
        ROLE_ARN = '<iam role to assume>'
	REGION = '<region; go us-east-1>'
);

SHOW CREATE CATALOG analytics_testing;
```

Until this is implemented, users are given the following error:

```
iceberg catalog with type glue is not supported
```

**Comment by sundy-li** [comment]
Maybe we should implement it in iceberg-rs and cc @Xuanwo.

**Comment by Xuanwo** [comment]
Already supported in https://github.com/apache/iceberg-rust/blob/main/crates/catalog/glue/README.md.

We need to integrate it inside databend.

**Comment by Rowlandev** [comment]
This has been included in Databend with [this](https://github.com/databendlabs/databend/pull/16824) pull request.

Thanks to @Xuanwo, @BohuTANG, @drmingdrmer & @sundy-li for the help.
