### ISSUE TITLE
flaky ci : 03_0016_update_with_lock

### ISSUE THREAD

**Issue by TCeason** [databendlabs/databend#16871]
**Summary**

https://github.com/databendlabs/databend/actions/runs/11909097295/job/33186928980?pr=16869

03_0016_update_with_lock:                                               [ FAIL ] - result differs with:
--- /runner/_work/databend/databend/tests/suites/0_stateless/03_dml/03_0016_update_with_lock.result	2024-11-19 08:57:08.718742621 +0000
+++ /runner/_work/databend/databend/tests/suites/0_stateless/03_dml/03_0016_update_with_lock.stdout	2024-11-19 08:58:49.993844498 +0000
@@ -1,3 +1,4 @@
 10
 Test table lock for update
-10
+Error: APIError: ResponseError with 4001: conflict resolve context:ModifiedSegmentExistsInLatest(SnapshotChanges { appended_segments: [], replaced_segments: {0: ("129/135/_sg/0c0ea9a049e74469ba9454511f42f837_v4.mpk", 4)}, removed_segment_indexes: [], merged_statistics: Statistics { row_count: 10, block_count: 1, perfect_block_count: 0, uncompressed_byte_size: 84, compressed_byte_size: 590, index_size: 669, col_stats: {0: ColumnStatistics { min: Number(1_i32), max: Number(10_i32), null_count: 0, in_memory_size: 42, distinct_of_values: None }, 1: ColumnStatistics { min: Number(2_i32), max: Number(11_i32), null_count: 0, in_memory_size: 42, distinct_of_values: None }}, cluster_stats: None }, removed_statistics: Statistics { row_count: 10, block_count: 1, perfect_block_count: 0, uncompressed_byte_size: 84, compressed_byte_size: 590, index_size: 672, col_stats: {0: ColumnStatistics { min: Number(1_i32), max: Number(10_i32), null_count: 0, in_memory_size: 42, distinct_of_values: None }, 1: ColumnStatistics { min: Number(2_i32), max: Number(11_i32), null_count: 0, in_memory_size: 42, distinct_of_values: None }}, cluster_stats: None } })

**Comment by TCeason** [comment]
cc @zhyass

**Comment by zhyass** [comment]
> cc @zhyass

Fixes by https://github.com/databendlabs/databend/pull/16907
