### ISSUE TITLE
Feature: query timeout setting

### ISSUE THREAD

**Issue by rad-pat** [databendlabs/databend#17020]
**Summary**
Query timeout if results not determined and returned in timeframe

Description for this feature.

Maybe this exists already, but I cannot find it through search. For the most part, queries are running fast, but then we get the odd rogue query that will take a long time - they can be investigated separately. However, when one of these queries is taking a long time, user may try running again one or more times and then query pod (in k8s) appears to be overloaded and then stop responding in timely fashion to other queries. We would like to set a query timeout value so that these long-running queries are removed if not results evaluated and returned in this timeframe. We call queries through Python BendSQL driver, http handler. Perhaps we missed something, but it appears that long-running queries just keep running.

**Comment by sundy-li** [comment]
is that `http_handler_result_timeout_secs` setting you want?

**Comment by zhang2014** [comment]
You can try setting `set max_execute_time_in_seconds = xx`.

**Comment by rad-pat** [comment]
> You can try setting `set max_execute_time_in_seconds = xx`.

👍 Fantastic, thankyou. I don't know why I could not see it myself.
