### ISSUE TITLE
Feature: Spill Index File

### ISSUE THREAD

**Issue by Xuanwo** [databendlabs/databend#17048]
**Summary**

Databend generates numerous temporary files when spilling. Currently, we use `list_objects` to retrieve the complete list and then call `delete_objects`, which involves many costly `list_objects` calls.

Therefore, I propose introducing a spill index file to record all temporary files created. This would allow us to remove them by reading this file's contents instead of using `list_objects`.

**Comment by sundy-li** [comment]
introduced in #17125  #17089
