### ISSUE TITLE
bug: Interval type, no comparison available

### ISSUE THREAD

**Issue by rad-pat** [databendlabs/databend#17056]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

v1.2.673

### What's Wrong?

I realise this is very new, but I'm trying to add new Interval type to Databend SQLAlchemy dialect and receive error message during test run.

```============================== 1 failed in 5.84s ===============================
FAILED [100%]
../../py312/lib/python3.12/site-packages/sqlalchemy/testing/suite/test_types.py:478 (IntervalTest_databend+databend_1_2_673.test_literal)
Traceback (most recent call last):
  File "/home/plaid/src/databend-sqlalchemy/databend_sqlalchemy/connector.py", line 190, in execute
    rows = self._db.query_iter(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: APIError: QueryFailed: [1065]error: 
  --> SQL:3:11
  |
1 | SELECT t.x 
2 | FROM t 
3 | WHERE t.x = to_interval('86404.0 seconds')
  |           ^ no function matches signature `eq(Interval NULL, Interval)`, you might need to add explicit type casts.

candidate functions:
  eq(Variant, Variant) :: Boolean                               : unable to unify `Interval NULL` with `Variant`
  eq(Variant NULL, Variant NULL) :: Boolean NULL                : unable to unify `Interval` with `Variant`
  eq(String, String) :: Boolean                                 : unable to unify `Interval NULL` with `String`
... and 31 more
```

### How to Reproduce?

```
CREATE TABLE t (
	x INTERVAL
);
INSERT INTO t (x) VALUES (to_interval('86404.0 seconds'));
INSERT INTO t (x) VALUES (NULL);
SELECT t.x 
FROM t 
WHERE t.x = to_interval('86404.0 seconds');
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
Yes we should support some interval function.

You can append in this issue 

https://github.com/databendlabs/databend/issues/17060

**Comment by TCeason** [comment]
The interval should not support a comparison.

e.g. 1 month and 28 days.

**Comment by TCeason** [comment]
> The interval should not support a comparison.
> 
> e.g. 1 month and 28 days.

In interval comparison, 

1 month will eq 30 days.
1 year will eq 12 months eq 360 days.

**Comment by TCeason** [comment]
Close with https://github.com/databendlabs/databend/pull/17093 finished.
