### ISSUE TITLE
bug:  `LOCATION` of `CREATE TABLE` does NOT work as expected 

### ISSUE THREAD

**Issue by dantengsky** [databendlabs/databend#17075]
**Summary**

Not sure if this is a documentation bug or a implementation bug:

when creating a table with external location, following the official doc:

https://docs.databend.com/sql/sql-commands/ddl/table/ddl-create-table-external-location#syntax

> CREATE TABLE [IF NOT EXISTS] [db.]table_name (
>     <column_name> <data_type> [NOT NULL | NULL] [{ DEFAULT <expr> }],
>     <column_name> <data_type> [NOT NULL | NULL] [{ DEFAULT <expr> }],
>     ...
> )
> LOCATION = 's3://<bucket>/[<path>]'
> CONNECTION = (
>     ENDPOINT_URL = 'https://<endpoint-URL>'
>     ACCESS_KEY_ID = '<your-access-key-ID>'
>     SECRET_ACCESS_KEY = '<your-secret-access-key>'
>     REGION = '<region-name>'
>     ENABLE_VIRTUAL_HOST_STYLE = 'true' | 'false'
> )
> |
> CONNECTION = (
>     CONNECTION_NAME = '<your-connection-name>'
> );

A table of invalid location could be created successfully, mutation and query are all work,

***But the table data is NOT stored at the specified location***.

Also: In section `Create a Table with External Location`
https://docs.databend.com/sql/sql-commands/ddl/table/ddl-create-table-external-location#create-a-table-with-external-location

A different syntax is used:

~~~
-- Create a table named `mytable` and specify the location `s3://testbucket/admin/data/` for the data storage
CREATE TABLE mytable (
  a INT
)
's3://testbucket/admin/data/'
CONNECTION = (
  ACCESS_KEY_ID = '<your_aws_key_id>',
  SECRET_ACCESS_KEY = '<your_aws_secret_key>',
  ENDPOINT_URL = 'https://s3.amazonaws.com'
);
~~~

**Reporduce:**

for example, a table of with invalid s3 location can be created (incorrectly):

~~~

mysql> select version();
+----------------------------------------------------------------------------------------+
| version()                                                                              |
+----------------------------------------------------------------------------------------+
| 8.0.26-v1.2.673-nightly-f777d195be(rust-1.85.0-nightly-2024-12-18T05:01:23.526505965Z) |
+----------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
Read 1 rows, 1.00 B in 0.007 sec., 153.02 rows/sec., 153.02 B/sec.

mysql> select * from system.configs where "group" = 'storage' and name = 'type';
+---------+------+-------+-------------+
| group   | name | value | description |
+---------+------+-------+-------------+
| storage | type | fs    |             |
+---------+------+-------+-------------+
1 row in set (0.03 sec)
Read 184 rows, 12.05 KiB in 0.008 sec., 21.89 thousand rows/sec., 1.40 MiB/sec.


mysql> create table t_location (c int) LOCATION = 's3 | bucket=non-exist-bucket,root=/,endpoint=https://s3.amazonaws.com';
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t_location values(1);
+-------------------------+
| number of rows inserted |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set (0.21 sec)
Read 1 rows, 5.00 B in 0.144 sec., 6.96 rows/sec., 34.81 B/sec.


mysql> select * from t_location;
+------+
| c    |
+------+
|    1 |
+------+
1 row in set (0.11 sec)
Read 1 rows, 5.00 B in 0.025 sec., 40.12 rows/sec., 200.61 B/sec.

~~~

**Comment by Xuanwo** [comment]
Hi, it's more like an implementation bug to me. fuse engines does support be stored in an external location but we didn't support it correctly. https://github.com/databendlabs/databend/pull/17076 is not a correct direction to me.

**Comment by SkyFan2002** [comment]
> Hi, it's more like an implementation bug. fuse engines does support be stored in an external location but we didn't support it correctly. #17076 is not a correct direction to me.

Yes, the fuse engine does support using an external location, but it employs a different syntax. The location= syntax was introduced in other features, and I guess it wasn't originally intended for the fuse engine to use this syntax as well. The question to discuss is whether we should make the fuse engine adopt this syntax too.

**Comment by SkyFan2002** [comment]
This is something I’m a bit concerned about　(╥﹏╥):  In the past, tables created with `location=` were stored in the default location instead of the intended external location. Allowing `location=` as valid syntax might cause confusion, as users wouldn't be able to easily distinguish whether a table is stored in the correct external location or the default one. Because neither the original SQL nor `SHOW CREATE TABLE` can distinguish between them.

**Comment by Xuanwo** [comment]
> Yes, the fuse engine does support using an external location, but it employs a different syntax.

What does the Fuse engine's syntax look like? I believe it would be better to use the same syntax for different engines.

> Allowing `location=` as valid syntax might cause confusion, as users wouldn't be able to easily distinguish whether a table is stored in the correct external location or the default one. Because neither the original SQL nor `SHOW CREATE TABLE` can distinguish between them.

For old tables, we should fix the output of `SHOW CREATE TABLE` to make it clear that this table is created on internal storage.
