### ISSUE TITLE
databend-query error start with Storageunavailable. Code: 39901, Text = can't clean temp dir:Permission denied (os error 13)

### ISSUE THREAD

**Issue by wubx** [databendlabs/databend#17080]
**Summary**
![image](https://github.com/user-attachments/assets/fb445d04-0c3b-479c-b65f-f9c389804cfa)

![image](https://github.com/user-attachments/assets/17cdf451-3e10-4c24-b1d4-a5bb1bb67c1b)
Databend Query start failure, caluse: Storageunavailable. Code: 39901, Text = can't clean temp dir:Permission denied (os error 13)

This hint is a little confusing what is it.

**Comment by TCeason** [comment]
https://github.com/databendlabs/databend/blob/7548f99a9b7b722c43218c2cbc055d7612cb313f/src/query/storages/common/cache/src/temp_dir.rs#L65

**Comment by wubx** [comment]
https://github.com/databendlabs/databend/blob/7548f99a9b7b722c43218c2cbc055d7612cb313f/src/query/config/src/config.rs#L3023-L3030

**Comment by forsaken628** [comment]
The current configuration of local spill is a bit complicated.
1. It is not enabled by default.
2. Configured spill_local_disk_path to enable it.
3. Configuring cache-disk-path will also enable it.

When enabled, it removes spill_local_disk_path as a backing mechanism for space cleanup.
This makes sense if spill_local_disk_path is an internally generated path.
But if it is not internally generated, but externally configured, deleting the path is unreasonable and should throw an error if the path does not exist.

Is there a best practice to make these logics a bit more standardized?

**Comment by wubx** [comment]
It might be a good idea to keep the separate.

**Comment by forsaken628** [comment]
update in #17103
