### ISSUE TITLE
bug: validity mask length must match the number of values

### ISSUE THREAD

**Issue by TCeason** [databendlabs/databend#17139]
### Search before asking

- [X] I had searched in the [issues](https://github.com/databendlabs/databend/issues) and found no similar issues.

### Version

main version and 651 nightly version

### What's Wrong?

nullable<type> may not be compatible

### How to Reproduce?

```sql


In main branch, debug build

create table test(id int);
insert into test values(1);

checkout version v1.2.651, debug build


:) select version();

SELECT version()

┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                            version()                                           │
│                                             String                                             │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Databend Query v1.2.651-nightly-4f79166feb(rust-1.81.0-nightly-2024-12-30T02:56:22.585948745Z) │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 0.023 sec. Processed 1 row, 1B (43.48 rows/s, 43B/s)


:) select * from test;

SELECT * FROM test

error: error happens after fetched 1 rows: APIError: QueryFailed: [1001]validity mask length must match the number of values

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
BT:

{"timestamp":"2024-12-30T11:01:58.458144+08:00","level":"INFO","query_id":"79bfb4ae-a99c-4ff3-8709-ba68a1582616","fields":{"message":"79bfb4ae-a99c-4ff3-8709-ba68a1582616: http query changing state from Running to Stopped, reason Err(FromStdError. Code: 1001, Text = validity mask length must match the number of values.\n\n   0: databend_common_exception::exception_backtrace::capture\n             at /data1/eason/databend/src/common/exception/src/exception_backtrace.rs:82:17\n   1: databend_common_exception::exception::ErrorCode<C>::from_std_error\n             at /data1/eason/databend/src/common/exception/src/exception.rs:291:24\n   2: databend_common_exception::exception_into::<impl core::convert::From<databend_common_arrow::arrow::error::Error> for databend_common_exception::exception::ErrorCode>::from\n             at /data1/eason/databend/src/common/exception/src/exception_into.rs:116:18\n   3: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/result.rs:1989:27\n   4: databend_common_storages_fuse::operations::read::native_data_source_deserializer::ReadPartState::read_page\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:174:46\n      databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform::read_and_check_prewhere\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:753:17\n   5: databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform::read_pages\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:664:17\n   6: <databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform as databend_common_pipeline_core::processors::processor::Processor>::process\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:1105:30\n   7: databend_common_pipeline_core::processors::processor::ProcessorPtr::process\n             at /data1/eason/databend/src/query/pipeline/core/src/processors/processor.rs:169:9\n   8: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs:169:9\n   9: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs:132:52\n  10: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_single_thread\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:406:35\n  11: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}::{{closure}}\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:50\n  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9\n  13: std::panicking::try::do_call\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40\n  14: __rust_try\n  15: std::panicking::try\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19\n      std::panic::catch_unwind\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14\n  16: databend_common_base::runtime::catch_unwind::catch_unwind\n             at /data1/eason/databend/src/common/base/src/runtime/catch_unwind.rs:47:11\n  17: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:34\n  18: databend_common_base::runtime::runtime_tracker::ThreadTracker::tracking_function::{{closure}}::{{closure}}\n             at /data1/eason/databend/src/common/base/src/runtime/runtime_tracker.rs:208:17\n  19: databend_common_base::runtime::thread::Thread::named_spawn::{{closure}}\n             at /data1/eason/databend/src/common/base/src/runtime/thread.rs:78:21\n  20: std::sys::backtrace::__rust_begin_short_backtrace\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:155:18\n  21: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:542:17\n  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9\n  23: std::panicking::try::do_call\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40\n  24: __rust_try\n  25: std::panicking::try\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19\n      std::panic::catch_unwind\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:541:30\n  26: core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/ops/function.rs:250:5\n  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9\n      std::sys::pal::unix::thread::Thread::new::thread_start\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/pal/unix/thread.rs:108:17\n  28: <unknown>\n  29: <unknown>\n)"}}
{"timestamp":"2024-12-30T11:01:58.458502+08:00","level":"INFO","query_id":"79bfb4ae-a99c-4ff3-8709-ba68a1582616","fields":{"message":"79bfb4ae-a99c-4ff3-8709-ba68a1582616: http query has change state to Stopped, reason Err(FromStdError. Code: 1001, Text = validity mask length must match the number of values.\n\n   0: databend_common_exception::exception_backtrace::capture\n             at /data1/eason/databend/src/common/exception/src/exception_backtrace.rs:82:17\n   1: databend_common_exception::exception::ErrorCode<C>::from_std_error\n             at /data1/eason/databend/src/common/exception/src/exception.rs:291:24\n   2: databend_common_exception::exception_into::<impl core::convert::From<databend_common_arrow::arrow::error::Error> for databend_common_exception::exception::ErrorCode>::from\n             at /data1/eason/databend/src/common/exception/src/exception_into.rs:116:18\n   3: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/result.rs:1989:27\n   4: databend_common_storages_fuse::operations::read::native_data_source_deserializer::ReadPartState::read_page\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:174:46\n      databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform::read_and_check_prewhere\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:753:17\n   5: databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform::read_pages\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:664:17\n   6: <databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform as databend_common_pipeline_core::processors::processor::Processor>::process\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:1105:30\n   7: databend_common_pipeline_core::processors::processor::ProcessorPtr::process\n             at /data1/eason/databend/src/query/pipeline/core/src/processors/processor.rs:169:9\n   8: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs:169:9\n   9: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs:132:52\n  10: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_single_thread\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:406:35\n  11: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}::{{closure}}\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:50\n  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9\n  13: std::panicking::try::do_call\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40\n  14: __rust_try\n  15: std::panicking::try\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19\n      std::panic::catch_unwind\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14\n  16: databend_common_base::runtime::catch_unwind::catch_unwind\n             at /data1/eason/databend/src/common/base/src/runtime/catch_unwind.rs:47:11\n  17: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:34\n  18: databend_common_base::runtime::runtime_tracker::ThreadTracker::tracking_function::{{closure}}::{{closure}}\n             at /data1/eason/databend/src/common/base/src/runtime/runtime_tracker.rs:208:17\n  19: databend_common_base::runtime::thread::Thread::named_spawn::{{closure}}\n             at /data1/eason/databend/src/common/base/src/runtime/thread.rs:78:21\n  20: std::sys::backtrace::__rust_begin_short_backtrace\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:155:18\n  21: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:542:17\n  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9\n  23: std::panicking::try::do_call\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40\n  24: __rust_try\n  25: std::panicking::try\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19\n      std::panic::catch_unwind\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:541:30\n  26: core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/ops/function.rs:250:5\n  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9\n      std::sys::pal::unix::thread::Thread::new::thread_start\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/pal/unix/thread.rs:108:17\n  28: <unknown>\n  29: <unknown>\n)"}}
{"timestamp":"2024-12-30T11:01:58.458936+08:00","level":"INFO","query_id":"79bfb4ae-a99c-4ff3-8709-ba68a1582616","fields":{"message":"http query reach end of blocks"}}
{"timestamp":"2024-12-30T11:01:58.461423+08:00","level":"INFO","query_id":"79bfb4ae-a99c-4ff3-8709-ba68a1582616","fields":{"message":"http query initial response to http query_id=79bfb4ae-a99c-4ff3-8709-ba68a1582616, state=ResponseState { has_result_set: Some(true), schema: [QueryResponseField { name: \"c1\", type: \"Nullable(UInt8)\" }], running_time_ms: 369, progresses: Progresses { scan_progress: ProgressValues { rows: 0, bytes: 0 }, write_progress: ProgressValues { rows: 0, bytes: 0 }, result_progress: ProgressValues { rows: 0, bytes: 0 }, total_scan: ProgressValues { rows: 1, bytes: 16 } }, state: Failed, affect: None, error: Some(FromStdError. Code: 1001, Text = validity mask length must match the number of values.\n\n   0: databend_common_exception::exception_backtrace::capture\n             at /data1/eason/databend/src/common/exception/src/exception_backtrace.rs:82:17\n   1: databend_common_exception::exception::ErrorCode<C>::from_std_error\n             at /data1/eason/databend/src/common/exception/src/exception.rs:291:24\n   2: databend_common_exception::exception_into::<impl core::convert::From<databend_common_arrow::arrow::error::Error> for databend_common_exception::exception::ErrorCode>::from\n             at /data1/eason/databend/src/common/exception/src/exception_into.rs:116:18\n   3: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/result.rs:1989:27\n   4: databend_common_storages_fuse::operations::read::native_data_source_deserializer::ReadPartState::read_page\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:174:46\n      databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform::read_and_check_prewhere\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:753:17\n   5: databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform::read_pages\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:664:17\n   6: <databend_common_storages_fuse::operations::read::native_data_source_deserializer::NativeDeserializeDataTransform as databend_common_pipeline_core::processors::processor::Processor>::process\n             at /data1/eason/databend/src/query/storages/fuse/src/operations/read/native_data_source_deserializer.rs:1105:30\n   7: databend_common_pipeline_core::processors::processor::ProcessorPtr::process\n             at /data1/eason/databend/src/query/pipeline/core/src/processors/processor.rs:169:9\n   8: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs:169:9\n   9: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs:132:52\n  10: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_single_thread\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:406:35\n  11: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}::{{closure}}\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:50\n  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9\n  13: std::panicking::try::do_call\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40\n  14: __rust_try\n  15: std::panicking::try\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19\n      std::panic::catch_unwind\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14\n  16: databend_common_base::runtime::catch_unwind::catch_unwind\n             at /data1/eason/databend/src/common/base/src/runtime/catch_unwind.rs:47:11\n  17: databend_query::pipelines::executor::query_pipeline_executor::QueryPipelineExecutor::execute_threads::{{closure}}\n             at /data1/eason/databend/src/query/service/src/pipelines/executor/query_pipeline_executor.rs:378:34\n  18: databend_common_base::runtime::runtime_tracker::ThreadTracker::tracking_function::{{closure}}::{{closure}}\n             at /data1/eason/databend/src/common/base/src/runtime/runtime_tracker.rs:208:17\n  19: databend_common_base::runtime::thread::Thread::named_spawn::{{closure}}\n             at /data1/eason/databend/src/common/base/src/runtime/thread.rs:78:21\n  20: std::sys::backtrace::__rust_begin_short_backtrace\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/backtrace.rs:155:18\n  21: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:542:17\n  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/panic/unwind_safe.rs:272:9\n  23: std::panicking::try::do_call\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:553:40\n  24: __rust_try\n  25: std::panicking::try\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panicking.rs:517:19\n      std::panic::catch_unwind\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/panic.rs:350:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/thread/mod.rs:541:30\n  26: core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/core/src/ops/function.rs:250:5\n  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/alloc/src/boxed.rs:2064:9\n      std::sys::pal::unix::thread::Thread::new::thread_start\n             at /rustc/cf2df68d1f5e56803c97d91e2b1a9f1c9923c533/library/std/src/sys/pal/unix/thread.rs:108:17\n  28: <unknown>\n  29: <unknown>\n), warnings: [] }, rows=0, next_page=None, sql='select * from t'"}}
{"timestamp":"2024-12-30T11:02:10.650960+08:00","level":"INFO","query_id":"53e30b86-3ab2-4519-90d9-5fd7a1898473","fields":{"message":"http query new request(from bendsql/0.24.4-2459693): HttpQueryRequest { session_id: None, session: Some(HttpSessionConf { database: Some(\"default\"), role: Some(\"account_admin\"), secondary_roles: None, keep_server_session_secs: None, settings: Some({}), txn_state: Some(AutoCommit), need_sticky: false, need_refresh: false, last_server_info: Some(ServerInfo { id: \"NiBvS4hF4JFqEdRmDg2qf6\", start_time: \"2024-12-30T11:01:49.557+08:00\" }), last_query_ids: [\"79bfb4ae-a99c-4ff3-8709-ba68a1582616\"], internal: None }), sql: \"select * from t\", pagination: PaginationConf { wait_time_secs: 10, max_rows_in_buffer: 5000000, max_rows_per_page: 10000 }, string_fields: true, stage_attachment: None }"}}

**Comment by TCeason** [comment]
in config.toml
```toml
# Storage config.
[storage]
# fs | s3 | azblob | obs | oss
type = "fs"
```

**Comment by sundy-li** [comment]
not reproduce , it's fixed in main
