### ISSUE TITLE
Replace TableMeta with TableInfo

### ISSUE THREAD

**Issue by drmingdrmer** [databendlabs/databend#2081]
can not agree more.

btw, the current `TableMeta` should be removed, or replaced by `TableInfo` IMO.

_Originally posted by @dantengsky in https://github.com/datafuselabs/databend/issues/2051#issuecomment-936251862_

**Comment by dantengsky** [comment]
This PR is being postponed, since it may heavily conflict with (sub-tasks of ) PR #2059 and #2091
