### ISSUE TITLE
Consider move `common/metatypes` to common/raft-store or other places

### ISSUE THREAD

**Issue by bohutang** [databendlabs/databend#2100]
**Summary**

- [x] Move `common/meta/src/*` to `common/meta/flight` crate
- [x] Move `common/metatypes` to `common/meta/types` crate
- [x] Move `common/raft-store` to `common/meta/raft-store` crate
- [x] Move `common/sled-store` to `common/meta/sled-store` crate
- [x] Move `common/kv` to `common/meta/local-store` crate
- [x] Move `common/kv-apis` to `common/meta/kv-apis` crate

**Comment by ariesdevil** [comment]
The original purpose of this mod was to provide type that both query and metasrv would use. Currently a small number of type definitions(eg: MetaVersion, NodeInfo) in the mod are used by both query and metasrv, not just for raft-store. But I think we can split out the raft-specific parts.
