### ISSUE TITLE
Consider remove common/meta/kv/kv_api_sync

### ISSUE THREAD

**Issue by bohutang** [databendlabs/databend#2110]
**Summary**

For a common library, we built in a runtime is not a good idea:
https://github.com/datafuselabs/databend/blob/a3faa8e85c886c343acddd7aec7182f43cbf5a24/common/meta/kv/util/src/store_runtime.rs#L31-L59

Since we have env setting in a common, it looks better to block the async as sync in the frontend, just like 
https://github.com/datafuselabs/databend/blob/a3faa8e85c886c343acddd7aec7182f43cbf5a24/query/src/catalogs/impls/meta_backends/remote_meta_backend.rs#L58

The timeout can be set from the config.

**Comment by BohuTANG** [comment]
@dantengsky If you agree, I will remove the block runtime from the common and block them in the frontend.
