### ISSUE TITLE
Add `get_table_info(&self)` for `Table` trait

### ISSUE THREAD

**Issue by sundy-li** [databendlabs/databend#2203]
**Summary**

Currently `to_table_info` needs `db` as an argument, but `Table`  should have a determinate DB name.

**Comment by sundy-li** [comment]
After talking with @drmingdrmer , I prefer to add `get_table_info()` into the trait Table.

And I'll move functions
-  `name()` 
- `get_id()`
- `schema()`
- `is_local`

as default trait functions since we already have `get_table_info()` method.

**Comment by dantengsky** [comment]
yeah, get_table_info could covert them all

**Comment by drmingdrmer** [comment]
Except database-id, a table should be able to work correctly without being aware any information about its belonging database.

Having a `db` in `TableInfo` is just a workaround for now.
