### ISSUE TITLE
[CLI] move view table command from sync to async

### ISSUE THREAD

**Issue by ZhiHanZ** [databendlabs/databend#2242]
**Summary**
the following command  would check health status for a databend cluster(currently support to be managed on local environment(
```
bendctl cluster view
```
for now, the table generation function run in synchronous way, which would probe on cluster health endpoint with several retries, and it may block result for a lot of time if the cluster has lots of unhealthy endpoints.

**Comment by BohuTANG** [comment]
We could rename the binary name from databend-cli to bendctl first cc @ZhiHanZ @PsiACE
