### ISSUE TITLE
Feature: Support running multiple sub-`Pipeline`s in a single query

### ISSUE THREAD

**Issue by leiysky** [databendlabs/databend#5265]
In databend, some transformations has dependency on other `Pipeline`s(e.g. join, subquery).

We need a mechanism to schedule `Pipeline`s from a transform.

So far, we can achieve this by spawning all `Pipeline`s concurrently. But this will run the `Pipelines` in different runtimes.

cc @zhang2014

**Comment by zhang2014** [comment]
We have supported scheduling multiple pipelines on one graph. Let's close it.
