### ISSUE TITLE
Looping over endpoints needs tests to ensure it works with unreachable endpoints and it returns an error if no endpoint is online.

### ISSUE THREAD

**Issue by drmingdrmer** [databendlabs/databend#5620]
This feature needs tests to ensure it works with unreachable endpoints and it returns an error if no endpoint is online.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/databend/pull/5616#pullrequestreview-986230798_

**Comment by BohuTANG** [comment]
The loop logic is a bit complexity, for the logic, I think it's easy to using 'for' instead.
