### ISSUE TITLE
Feature: introduce row format to optimize hash join and sort operator

### ISSUE THREAD

**Issue by xudong963** [databendlabs/databend#7214]
**Summary**

I'll give a RFC later

**Comment by xudong963** [comment]
Tpch sql18's flamegraph

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/41979257/197570539-81eec2fd-bfb1-47df-aa39-bd887f256eae.png">

Row format will speed up `block_take_by_chunk_indice`

**Comment by sundy-li** [comment]
row format is assigned to @RinChanNOWWW , sort need this.

**Comment by xudong963** [comment]
Add the issue to https://github.com/datafuselabs/databend/issues/8074, I think tpch q18 need row format to speed up.
